/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.developerphil.gw

import java.nio.file.FileSystems


fun main(args: Array<String>) {
    val executableLocation = FileSystems.getDefault().gradlePath()
    val arguments = args.parseArguments()

    runCommand("$executableLocation $arguments")
}

fun runCommand(command: String) {
    println(command)
}
