/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.developerphil.gw

import assertk.assertThat
import assertk.assertions.isEqualTo
import kotlin.test.Test

class ArgsConverterTest {

    @Test
    fun `Can represent the argument array as a space delimited string`() {
        assertThat(arrayOf("tasks").parseArguments()).isEqualTo("tasks")
        assertThat(arrayOf("clean assemble").parseArguments()).isEqualTo("clean assemble")
        assertThat(arrayOf("").parseArguments()).isEqualTo("")
    }

}

